//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFReports.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFReports.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string CodeTab {
            get {
                return ResourceManager.GetString("CodeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compile.
        /// </summary>
        public static string CompileButton {
            get {
                return ResourceManager.GetString("CompileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string DesignerButton {
            get {
                return ResourceManager.GetString("DesignerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplayButton {
            get {
                return ResourceManager.GetString("DisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layout.
        /// </summary>
        public static string LayoutTab {
            get {
                return ResourceManager.GetString("LayoutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load.
        /// </summary>
        public static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open reports (widgets) designer or display.
        /// </summary>
        public static string MainMenuLabel {
            get {
                return ResourceManager.GetString("MainMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        public static string PreviewButton {
            get {
                return ResourceManager.GetString("PreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget name:.
        /// </summary>
        public static string WidgetNameLabel {
            get {
                return ResourceManager.GetString("WidgetNameLabel", resourceCulture);
            }
        }
    }
}
