//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFReports.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Snippets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Snippets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFReports.Properties.Snippets", typeof(Snippets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void Run()
        ///{
        ///    //code for getting data here
        ///    
        ///}
        ///
        /////put methods properties and fields here.
        /// </summary>
        public static string DefaultCode {
            get {
                return ResourceManager.GetString("DefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grid xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:local=&quot;clr-namespace:ReportLoader;assembly=ReportLoader&quot;
        ///	xmlns:controls=&quot;clr-namespace:ReportLoader;assembly=ReportLoader&quot;
        ///    xmlns:charts=&quot;clr-namespace:De.TorstenMandelkow.MetroChart;assembly=De.TorstenMandelkow.MetroChart&quot;
        ///    x:Name=&quot;Page1&quot;&gt;
        ///	&lt;Grid.Resources&gt; 
        ///		 
        ///	&lt;/Grid.Resources&gt;
        ///	&lt;Grid.RowDefinitions&gt;
        ///		&lt;RowDefinition/&gt;
        ///	&lt;/Grid.RowDefinitions&gt;
        ///	&lt;G [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultLayout {
            get {
                return ResourceManager.GetString("DefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;controls:HeaderControl Style=&quot;{{StaticResource {0}}}&quot; Header=&quot;&quot; Content=&quot;&quot; Color=&quot;&quot; /&gt;.
        /// </summary>
        public static string HeaderControlControl {
            get {
                return ResourceManager.GetString("HeaderControlControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeaderControl.
        /// </summary>
        public static string HeaderControlLabel {
            get {
                return ResourceManager.GetString("HeaderControlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Style x:Key=&quot;{0}&quot; TargetType=&quot;{{x:Type controls:HeaderControl}}&quot;&gt;
        ///	&lt;Setter Property=&quot;Template&quot;&gt;
        ///		&lt;Setter.Value&gt;
        ///			&lt;ControlTemplate TargetType=&quot;{{x:Type controls:HeaderControl}}&quot;&gt;
        ///				&lt;Grid Background=&quot;{{TemplateBinding Background}}&quot;&gt;
        ///					&lt;Grid.RowDefinitions&gt;
        ///						&lt;RowDefinition Height=&quot;Auto&quot;/&gt;
        ///						&lt;RowDefinition Height=&quot;*&quot;/&gt;
        ///					&lt;/Grid.RowDefinitions&gt;
        ///					&lt;Grid.ColumnDefinitions&gt;
        ///						&lt;ColumnDefinition Width=&quot;Auto&quot;/&gt;
        ///						&lt;ColumnDefinition Width=&quot;*&quot;/&gt;
        ///					&lt;/Grid.ColumnDefinitions&gt;
        ///					&lt;Rectang [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeaderControlStyle {
            get {
                return ResourceManager.GetString("HeaderControlStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private object myProperty
        ///
        ///public object MyProperty
        ///{
        ///	get { return myProperty;}
        ///	set 
        ///	{ 
        ///		if(value == myProperty) return;
        ///		myProperty = value;
        ///		RaisePropertyChanged();
        ///	}
        ///}.
        /// </summary>
        public static string ViewModelPropertySnippet {
            get {
                return ResourceManager.GetString("ViewModelPropertySnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        public static string ViewModelPropertySnippetName {
            get {
                return ResourceManager.GetString("ViewModelPropertySnippetName", resourceCulture);
            }
        }
    }
}
